export const data = [
  {
    id: 1,
    name_сyrillic: "Meade Rankling",
    name_latin: "Nata Hiscocks",
    gender: "Female",
    birthday: "21.05.2019",
    eisu: "845488444-0",
    group: 83,
    room: 65,
    dorm: 14,
    comment: "neque",
  },
  {
    id: 2,
    name_сyrillic: "Huntley Abramson",
    name_latin: "Paxon Sambath",
    gender: "Male",
    birthday: "21.09.2021",
    eisu: "017411392-7",
    group: 24,
    room: 91,
    dorm: 96,
    comment: "diam neque vestibulum eget",
  },
  {
    id: 3,
    name_сyrillic: "Chevy Leach",
    name_latin: "Torrin D'Ambrogi",
    gender: "Male",
    birthday: "06.04.2019",
    eisu: "648024975-5",
    group: 74,
    room: 23,
    dorm: 44,
    comment:
      "purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor",
  },
  {
    id: 4,
    name_сyrillic: "Neale Bowness",
    name_latin: "Waylin Kase",
    gender: "Male",
    birthday: "18.04.2022",
    eisu: "566803100-4",
    group: 85,
    room: 80,
    dorm: 10,
    comment:
      "sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl",
  },
  {
    id: 5,
    name_сyrillic: "Maison Klos",
    name_latin: "Bax Argontt",
    gender: "Male",
    birthday: "18.04.2019",
    eisu: "204907416-6",
    group: 1,
    room: 57,
    dorm: 33,
    comment: "turpis integer aliquet massa id lobortis convallis",
  },
  {
    id: 6,
    name_сyrillic: "Gertie Oldacres",
    name_latin: "Astra Bemrose",
    gender: "Female",
    birthday: "15.03.2018",
    eisu: "690783525-8",
    group: 7,
    room: 64,
    dorm: 76,
    comment:
      "enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu",
  },
  {
    id: 7,
    name_сyrillic: "Alister Gaudin",
    name_latin: "Donnell Coulthart",
    gender: "Male",
    birthday: "08.09.2021",
    eisu: "744555120-4",
    group: 13,
    room: 77,
    dorm: 5,
    comment:
      "consequat lectus in est risus auctor sed tristique in tempus sit amet sem",
  },
  {
    id: 8,
    name_сyrillic: "Wilbur Holliar",
    name_latin: "Remus Verheyden",
    gender: "Male",
    birthday: "27.05.2018",
    eisu: "425625097-2",
    group: 31,
    room: 91,
    dorm: 26,
    comment:
      "sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien",
  },
  {
    id: 9,
    name_сyrillic: "Monty Danniel",
    name_latin: "Beauregard de Verson",
    gender: "Male",
    birthday: "14.10.2022",
    eisu: "264111714-2",
    group: 81,
    room: 66,
    dorm: 1,
    comment:
      "iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget",
  },
  {
    id: 10,
    name_сyrillic: "Janenna Kwietek",
    name_latin: "Vivian Hacquoil",
    gender: "Female",
    birthday: "13.11.2021",
    eisu: "660314636-3",
    group: 40,
    room: 11,
    dorm: 53,
    comment:
      "neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor",
  },
];
